### ISSUE TITLE
Loading as druid (non cat) doesn't work

### ISSUE THREAD

**Issue by illumis2** [nullfoxh/SlyFox#1]
If you log in or reload ui while in non cat form, i.e tauren / nightelf mode then the addon will not appear and work when you shift into cat form. However if you log in as cat form or reload while in cat form the addon works fine.

**Comment by nullfoxh** [comment]
Guess I broke it with the latest update. When you log in while out of form, will it work after you shift to form though? Or do you need reloadui?

**Comment by nullfoxh** [comment]
Yeah, made a typo earlier. Should be fixed now. Didn't get to test it, but please lemme know if it works :)

**Comment by illumis2** [comment]
I've done a bit more testing and it seems like the problem is fixed!

**Comment by nullfoxh** [comment]
Nice! Thanks for the report and testing!
